# Generated by Django 3.0.4 on 2020-03-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workfair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.TextField(default=''),
        ),
    ]
