# Generated by Django 3.0.4 on 2020-03-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workfair', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isEmployer',
            field=models.BooleanField(default=False),
        ),
    ]
