# Generated by Django 3.0.4 on 2020-03-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workfair', '0005_auto_20200322_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=32),
        ),
    ]
