# Generated by Django 3.0.4 on 2020-03-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workfair', '0007_auto_20200322_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='competences',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
