# Generated by Django 3.0.4 on 2020-03-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workfair', '0008_auto_20200322_1304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
