# Generated by Django 3.0.4 on 2020-03-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workfair', '0010_applicantprofile_employerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='username',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='username',
            field=models.CharField(default='', max_length=32),
        ),
    ]
