# Generated by Django 3.0.4 on 2020-03-28 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workfair', '0011_auto_20200328_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
