# Generated by Django 3.0.4 on 2020-04-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workfair', '0018_vacancy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workfair.EmployerProfile'),
        ),
    ]
