# Generated by Django 3.0.4 on 2020-04-01 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workfair', '0019_auto_20200401_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workfair.EmployerProfile'),
        ),
    ]
