# Generated by Django 3.1.7 on 2021-03-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workfair', '0020_auto_20200402_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='viewsAmount',
            field=models.IntegerField(default=0),
        ),
    ]
