# Generated by Django 3.1.7 on 2021-03-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workfair', '0021_vacancy_viewsamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='creationDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
