# Generated by Django 3.1.7 on 2021-03-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workfair', '0022_vacancy_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='phoneNumber',
            field=models.IntegerField(default=89990870968),
        ),
    ]
